baseurl: /ahmedabad
permalink: pretty
markdown: kramdown
paginate: 5
repo: ahmedabad
github_org: maptime
future:true
maptime:
  chapter: MaptimeAMD
  twitter: MaptimeAMD
  #disqus: YOUR DISQUS USERNAME
