baseurl: /ahmedabad
permalink: pretty
markdown: kramdown
future: true
paginate: 5
repo: ahmedabad
github_org: maptime
maptime:
  chapter: MaptimeAMD
  twitter: MaptimeAMD
  #disqus: YOUR DISQUS USERNAME
